### ISSUE TITLE
Request: make @ngneat/spectator opt-in 

### ISSUE THREAD

**Issue by lacolaco** [ngneat/lib#1]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

This project looks awesome! I've tried to add `@ngneat/lib` to my new library project but its schematics said `@ngneat/spectator` was not found.
I want just to generate a starter of an Angular library so other libraries are not needed.

## Expected behavior

I want to run commands like below;

```
$ ng new my-library --no-create-application && cd my-library
$ ng add @ngneat/lib @scope/my-library
```

**Comment by itayod** [comment]
> This project looks awesome!

Thanks, @lacolaco

> I've tried to add @ngneat/lib to my new library project but its schematics said @ngneat/spectator was not found

Seems weird I will try to check that out, meantime could you install `@ngneat/spectator` before you run 
`$ ng add @ngneat/lib @scope/my-library` and see if it works?

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74084912-3f518880-4ab7-11ea-9c71-9822bc2b5138.png)

After executing `yarn add -D @ngneat/spectator`, it works perfectly.

**Comment by lacolaco** [comment]
FYI https://github.com/ngneat/lib/blob/master/src/lib/create-lib.ts#L22-L39

**Comment by itayod** [comment]
fixed by https://github.com/ngneat/lib/pull/6
