### ISSUE TITLE
Can't build library when @ngneat/dialog imported

### ISSUE THREAD

**Issue by fstodulski** [ngneat/lib#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
After running `npm run build:lib` getting an error

<pre>code>

✖ Compiling TypeScript sources through NGC
ERROR: Unexpected value 'undefined' declared by the module 'DialogModule in /Users/franciszekstodulski/develop/ngx-tetrisly/node_modules/@ngneat/dialog/ngneat-dialog.d.ts'

An unhandled exception occurred: Unexpected value 'undefined' declared by the module 'DialogModule in /Users/franciszekstodulski/develop/ngx-tetrisly/node_modules/@ngneat/dialog/ngneat-dialog.d.ts'

</code></pre>

## Expected behavior
It should build.

## Minimal reproduction of the problem with instructions
1. Create a new angular project without application
2. Run `ng add @ngneat/lib <lib_name>`
3. Run `npm i @ngneat/dialog` (ng add doesn't work for libraries).
4. Add DialogModule to main.module and export in in publi_api.ts
5. Run `npm run build:lib`

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 11.0.7
Node: 14.15.1
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.2.2
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
ng-packagr                      11.2.4
rxjs                            6.6.6
typescript                      4.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.15.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
See https://github.com/ngneat/dialog/issues/21

**Comment by fstodulski** [comment]
Unfortunately this one doesn't work with the newest Angular

<pre><code>
➜ node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot --build-optimizer
Unknown option: '--aot'
Unknown option: '--build-optimizer'
<code><pre>
