### ISSUE TITLE
Issue with running schematics on the 12 version of angular due to deprecating tslint.

### ISSUE THREAD

**Issue by va-stefanek** [ngneat/lib#24]
## Issue with running schematics on the 12 version of angular due to deprecating tslint.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
 I got following error when running `ng add @ngneat/lib @scope/toaster`
```
TSLint's support is discontinued and we're deprecating its support in Angular CLI.
To opt-in using the community driven ESLint builder, see: https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint.
An unhandled exception occurred: Unable to find TSLint. Ensure TSLint is installed.
See "/tmp/ng-3QYQop/angular-errors.log" for further details.
Command failed: npm run lint -- --fix @scope/toaster
TSLint's support is discontinued and we're deprecating its support in Angular CLI.
To opt-in using the community driven ESLint builder, see: https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint.
An unhandled exception occurred: Unable to find TSLint. Ensure TSLint is installed.
See "/tmp/ng-3QYQop/angular-errors.log" for further details.
```

## Expected behavior

Replace tslint with ESLint.

## Minimal reproduction of the problem with instructions
Run `ng add @ngneat/lib @scope/toaster` on the project with angular 12.

## Environment

<pre><code>
Angular version: 12.0.0

**Comment by NetanelBasal** [comment]
@shhdharmen can we update to ng12, please?

**Comment by va-stefanek** [comment]
I might also help if you want :)

**Comment by shhdharmen** [comment]
> I might also help if you want :) 

Sure, PR is most welcome... 😊

**Comment by shhdharmen** [comment]
This beta release will still not work, because `@ngneat/spectator` is not compatible with v12.

Waiting for https://github.com/ngneat/spectator/issues/442 to get closed, once that's done we can refactor, verify and and make a new release.

**Comment by NetanelBasal** [comment]
@shhdharmen it's done.

**Comment by shhdharmen** [comment]
Sure, I will try to complete this weekend.
