### ISSUE TITLE
Feedback based on my use/open discussion for new features

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/lib#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Below are things I had to tweak to the configuration of the library to make it prod-ready. I believe that these changes could be applied to any library, but some of the things below are subjective.

### 1. husky git hooks weren't working for me
**Description:** during the installation of dependencies it probably printed out an error or a warning mentioning that the version of git I'm using isn't high enough (`Husky requires Git >= 2.13.2`). I didn't see this error because of the amount of output being printed during the installation of dependencies. Because of this, I spent extra time trying to understand why husky hooks aren't being run.

**Proposed fix:** I don't think you can specify the version of the git in the [engines](https://docs.npmjs.com/files/package.json#engines) prop of `package.json`. Perhaps this could work: https://www.npmjs.com/package/packdoc

### 2. Build a prod version of the library.
**Description:** The [basic workflow](https://github.com/ngneat/lib#basic-working-flow) recommends running `npm run build:lib` before publishing. This won't work though since in default mode Angular will build the library using ivy. As of now, Ivy libraries should not be published to npm.

**Proposed fix:** add `--prod` to the `"build:lib"` script

### 3. The root `README.md` and `logo.svg` should be copied to the dist folder
**Description:** When publishing the package to npm, it takes everything from the `dist/my-lib` folder and makes that THE package. When that arrives to npm and a user goes to the npmjs.org to see the package, either wrong files are displayed or they're completely missing. This is currently a problem with THIS package: https://www.npmjs.com/package/@ngneat/lib

**Proposed fix:**
* add a dependency to `copyfiles` so that copying works across different platforms.
* add script: `"postbuild:lib": "copyfiles README.md logo.png dist/[my-lib]"`

### 4. Stricter `tsconfig.json`
**Description:** I know, this one kind of depends on each developer, but I feel that the stricter options really contribute to the code quality.

**Proposed fix:**
Here are the options I always use in my projects:
```json
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true,
    "strictPropertyInitialization": false,
```
`strictPropertyInitialization` is `false` because often in Angular people initialize properties in the `ngAfterViewInit()`

### 5. Changes to `tslint.json`
1. This one goes along with stricter `tsconfig.json`.
    Add rule `"no-unused-variable": true,`
1. Because rules now prohibit unused arguments, add a way to override that if really need to via _:
    Add `"allow-leading-underscore"` to `"variable-name"` > "options".
1. Remove the following rules because these options are now controlled by prettier to avoid conflicting behavior when formatting:
```json
"curly": true,
"eofline": true,
"import-spacing": true,
"indent": { ... },
"max-line-length": [true, 140],
"quotemark": [ ... ],
"semicolon": { ... },
"typedef-whitespace": { ... },
"whitespace": { ... }
```

**Comment by itayod** [comment]
@DmitryEfimenko Hi, sounds good, would you like to create a PR?

**Comment by DmitryEfimenko** [comment]
sure, I'm on it.

One more item: I find myself constantly having to go check the [workflow](https://github.com/ngneat/lib#basic-working-flow) section docs while working on my library. It might make sense to include this section in the generated README.md file.

**Comment by itayod** [comment]
Thanks, @DmitryEfimenko good idea feel free to add it :)

**Comment by itayod** [comment]
@DmitryEfimenko any progress?

**Comment by DmitryEfimenko** [comment]
Got buried with other projects. No progress so far. Sorry about that.
