### ISSUE TITLE
Travis configuration isn't generated

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/lib#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The [Tools](https://github.com/ngneat/lib#tools) section of the `README.md` mentions the use of Travis. However, I didn't see anything related to Travis generated after the use of the schematic.

## Expected behavior

Travis configuration should be generated

## Minimal reproduction of the problem with instructions

Just run schematics on top of a brand new empty angular workspace.

## What is the motivation / use case for changing the behavior?

It'd be great to automatically run unit tests for pull requests.

For Tooling issues:
- Node version: 12
- Platform:  Windows

**Comment by itayod** [comment]
Thanks @DmitryEfimenko, looks like that's might be a bug, but we actually prefer to switch that and use github actions instead...

would you like to open a PR for it?

**Comment by DmitryEfimenko** [comment]
hmm, that might be a good opportunity to finally dive deep into these Actions. I'll try to do a PR if no one gets to this before me.

**Comment by DmitryEfimenko** [comment]
for my own education, why is the preference to switch to Github Actions and not use Travis?

**Comment by itayod** [comment]
because it's built-in tool
