### ISSUE TITLE
No work with Angular 10

### ISSUE THREAD

**Issue by tonivj5** [ngneat/lib#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
It crashes on `ng add`

## Expected behavior
It works

## Minimal reproduction of the problem with instructions
```sh
npx @angular/cli new test-lib
cd test-lib
npm run ng add @ngneat/lib test
```

When add repository's url it fails:
```sh
$ ng add @ngneat/lib test
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? What is you repository's host url? (https://github.com/...) https://github.com/test
Unexpected token / in JSON at position 0
error Command failed with exit code 1.
``` 
## Environment

<pre><code>
Angular version: 10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.5.0
- Platform:  Linux

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
@itayod, please take care.

**Comment by itayod** [comment]
Hi @tonivj5 could you check it out now?

**Comment by tonivj5** [comment]
It adds the project now :+1:

But it shows a lot of errors start:
![image](https://user-images.githubusercontent.com/7110786/86944228-b8790880-c147-11ea-9fdb-c07c8b9a86ab.png)
And in editor (I think related to https://github.com/angular/angular-cli/issues/18040)
![image](https://user-images.githubusercontent.com/7110786/86944511-26bdcb00-c148-11ea-8a80-e609c65edeb4.png) 
doesn't like `inlineSources` in `tsconfig.lib.json`
![image](https://user-images.githubusercontent.com/7110786/86944411-07bf3900-c148-11ea-918c-78ddb1dc61bb.png)

And npm shows some warnings (I think we should use a more recent version of `spectator`):
![image](https://user-images.githubusercontent.com/7110786/86944736-713f4780-c148-11ea-91cc-ea3e429078d1.png)

Steps to reproduce:
```sh
npx @angular/cli new test-lib
cd test-lib
npm run ng add @ngneat/lib test
npm run start
```

**Comment by itayod** [comment]
@tonivj5 I think I have found the problem... could you install the latest version and try again? thanks!

**Comment by tonivj5** [comment]
@itayod it works like a charm :+1:

**Comment by itayod** [comment]
@tonivj5 thanks man :)
